### ISSUE TITLE
docx格式无法获取无法选中的数字

### ISSUE THREAD

**Issue by Arrake-One** [yangzhongke/yzk18#1]
# 如图，这样无法选中的数字，无法获取
![image](https://user-images.githubusercontent.com/67113472/118347569-e5235b00-b576-11eb-9fcc-dd22605f31c2.png)
# 运行结果：
使用WordHelpers.readAlltext方法
![image](https://user-images.githubusercontent.com/67113472/118347621-392e3f80-b577-11eb-9527-fc496f6e71ee.png)
# 原因分析：
## 前言
之前我从解析dom的角度，解析过docx格式的文件，但现在忘记了一些细节，当时因为一些特殊的需求，发现使用poi的api无法实现，于是自己就试着造轮子了。。。现在，想看看别人的解析思路是怎么样的。。。
之前项目的地址：https://gitee.com/arrake/word-analysis
下面的话我从自己解析dom的角度，分析是怎么解析出数字的，还请前辈多多指教
### 为什么可以使用dom解析？
在本质上docx文件，是一个压缩文件，只要改一下文件后缀解压，就行了
![image](https://user-images.githubusercontent.com/67113472/118349291-73510e80-b582-11eb-8b3f-c03b2270a092.png)
### 关于解压文件目录的说明
![image](https://user-images.githubusercontent.com/67113472/118349309-924fa080-b582-11eb-88a9-a832a38342ef.png)
到目前为止，我用到的只要word/目录下的文件，也就是说，word目录下的文件可以满足读写的需求
但还要说明的是，要一些文件是不可确实的，具体可以查看上面项目的resource/docxTemplate下的文件，如图：
![image](https://user-images.githubusercontent.com/67113472/118349573-02aaf180-b584-11eb-8360-9f6963d1d55f.png)
也可以通过这个链接自己查看项目，不过要登录码云
[链子](https://gitee.com/-/ide/project/arrake/word-analysis/edit/master/-/io/src/main/resources/docxTemplate/[Content_Types].xml)
### 正文
1、word/document.xml 主要的文本，通过这里面的标签，可以链接到其他的文件
![image](https://user-images.githubusercontent.com/67113472/118349728-0b4ff780-b585-11eb-9ea6-0d4a4c58d700.png)
2、word/numbering 映射对应的数字列表
![image](https://user-images.githubusercontent.com/67113472/118349797-87e2d600-b585-11eb-8450-9006f0d96dba.png)
具体地映射规则，通过numId映射到abstractNumId，最后在对应的标签内获取它具体的样式，包括开始值，数字类型等
3、在document.xml获取文本numId
![image](https://user-images.githubusercontent.com/67113472/118349959-97165380-b586-11eb-8f2c-1a097d223bcc.png)
[具体替换的代码](https://gitee.com/-/ide/project/arrake/word-analysis/edit/master/-/io/src/main/java/com/arrake/utils/FormatToReplace.java)
![image](https://user-images.githubusercontent.com/67113472/118350092-831f2180-b587-11eb-94ea-c3ce8035d8b0.png)

**Comment by Arrake-One** [comment]
案例文件
[test.docx](https://github.com/yangzhongke/yzk18/files/6483053/test.docx)

**Comment by yangzhongke** [comment]
谢谢反馈，严格来讲这个也不算bug。就像html的<ol></ol>也不能直接获取编号的文本一样。以后看情况再决定是否支持这个吧。
