### ISSUE TITLE
关于 “Part2-3 Maven的使用” 这一节课的反馈

### ISSUE THREAD

**Issue by HongXiao1923** [yangzhongke/yzk18#2]
反馈课程中杨老师可能忽略的一个点：关于Maven的配置问题，初学者在这地方遇到报错可能都不知道怎么解决，比如 fail to read……   fail to transfer…… 等。
像我今天就是遇到了这个问题，先是按教程导入杨老师的you18-commons，之后Maven显示Project不能启动，然后我就去SCDN找了各种解决方法，花了几小时的时间，像是各种镜像的配置啊，clean-->stall 啊，reload啊都试了没一点用，自己还怀疑是网络的问题，还把VPN反复关闭重开多次（挂VPN不用配置maven镜像也能下载jar包）人都开玩崩溃的那种，就差卸载IDEA重装了。最后，总算是看到了一篇关于文件位置配置的帖子，我现有的jar包都是放在C盘的respority目录下的，而很久以前的Maven是安装在D盘上的（带bin和conf），这才幡然醒悟，于是把setting.xml放到了D盘目录下，重新在D盘下配置resperity这才成功加载了课程的jar包。
经过自己几个小时的折腾，才发现课程中杨老师一开始就没有讲解Maven的安装（以前做过springboot也是不要Maven配置的，于是自己也忽略了这一点）。如果大家能看到的话，也算是给大家填了一个坑，当然Java到处都是坑，hah！
可能初学者在Maven配置这地方都不知道该怎么做，最后导致Maven配置不成功。这可能也是这个yzk-commons使用量不高的一个原因。

**Comment by yangzhongke** [comment]
谢谢，maven不是IDEA内置的吗？默认都安装maven了吧。

**Comment by HongXiao1923** [comment]
> 

那这应该是我电脑自己的问题，我的确是把setting.xml重新放了一个位置才解决了问题。如果有同学也遇到同样的问题的话，我的解决办法希望对他们有所帮助。
希望杨老师可以持续更新Java课程，课程质量很高！！
