### ISSUE TITLE
Feature Requested:  to support TLS

### ISSUE THREAD

**Issue by PackFan2019** [yangzhongke/yzk18#3]
Thank you very much for your library.  Hopefully you enjoy your life in New Zealand.

This is no issue, just a new feature requested.  

Is there any chance to add TLS support to your Email Sender since most email providers in USA require that?  

The key code may be like below: 
          
  properties.put("mail.smtp.starttls.enable", true);
        properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
            properties.put("mail.smtp.auth", true);

**Comment by yangzhongke** [comment]
All done.
An overloaded version of 'send' was added:
```
public void send(Properties extraProperties)
```

please update the maven package to the latest version.
